import type { Config } from 'tailwindcss';
export default {
  darkMode: 'class',
  future: { hoverOnlyWhenSupported: true },
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Georgia', 'Cambria', '"Times New Roman"', 'serif'],
      },
      transitionDuration: {
        instant: 'var(--motion-instant)',
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
        slow: 'var(--motion-slow)',
        slower: 'var(--motion-slower)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        exit: 'var(--ease-exit)',
        emphasis: 'var(--ease-emphasis)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'rise-in': { from: { opacity: '0', transform: 'translate3d(0,8px,0)' }, to: { opacity: '1', transform: 'none' } },
        'pop-in': { from: { opacity: '0', transform: 'scale(.94)' }, to: { opacity: '1', transform: 'none' } },
        'sheet-in': { from: { transform: 'translate3d(0,100%,0)' }, to: { transform: 'none' } },
        'sheet-out': { from: { transform: 'none' }, to: { transform: 'translate3d(0,16px,0)' } },
        'modal-out': { from: { opacity: '1', transform: 'scale(1)' }, to: { opacity: '0', transform: 'scale(.96)' } },
        'toast-in': { from: { opacity: '0', transform: 'translate3d(-12px,0,0) scale(.97)' }, to: { opacity: '1', transform: 'none' } },
        'toast-out': { from: { opacity: '1', transform: 'none' }, to: { opacity: '0', transform: 'translate3d(-8px,0,0)' } },
        'toast-countdown': { from: { transform: 'scaleX(1)' }, to: { transform: 'scaleX(0)' } },
        shimmer: { from: { transform: 'translate3d(-100%,0,0)' }, to: { transform: 'translate3d(100%,0,0)' } },
        'draw-check': { from: { strokeDashoffset: '24' }, to: { strokeDashoffset: '0' } },
      },
      animation: {
        'fade-in': 'fade-in var(--motion-base) var(--ease-standard) both',
        'rise-in': 'rise-in var(--motion-base) var(--ease-standard) both',
        'pop-in': 'pop-in var(--motion-fast) var(--ease-emphasis) both',
        'sheet-in': 'sheet-in var(--motion-slow) var(--ease-standard) both',
        'sheet-out': 'sheet-out var(--motion-fast) var(--ease-exit) both',
        'modal-out': 'modal-out var(--motion-fast) var(--ease-exit) both',
        'toast-in': 'toast-in var(--motion-base) var(--ease-standard) both',
        'toast-out': 'toast-out var(--motion-fast) var(--ease-exit) both',
        'toast-countdown': 'toast-countdown var(--toast-timeout, 4s) linear both',
        shimmer: 'shimmer 1400ms linear infinite',
        'draw-check': 'draw-check var(--motion-base) var(--ease-standard) both',
      },
      colors: {
        canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
        overlay: 'rgb(var(--color-overlay) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-raised': 'rgb(var(--color-surface-raised) / <alpha-value>)',
        field: 'rgb(var(--color-field) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        subtle: 'rgb(var(--color-subtle) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--color-accent-hover) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
        'accent-soft': 'rgb(var(--color-accent-soft) / <alpha-value>)',
        'accent-soft-border': 'rgb(var(--color-accent-soft-border) / <alpha-value>)',
        'accent-soft-foreground': 'rgb(var(--color-accent-soft-foreground) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        'success-soft': 'rgb(var(--color-success-soft) / <alpha-value>)',
        'success-border': 'rgb(var(--color-success-border) / <alpha-value>)',
        'success-foreground': 'rgb(var(--color-success-foreground) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'error-hover': 'rgb(var(--color-error-hover) / <alpha-value>)',
        'error-soft': 'rgb(var(--color-error-soft) / <alpha-value>)',
        'error-border': 'rgb(var(--color-error-border) / <alpha-value>)',
        'error-foreground': 'rgb(var(--color-error-foreground) / <alpha-value>)',
        'error-solid-foreground': 'rgb(var(--color-error-solid-foreground) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-border': 'rgb(var(--color-warning-border) / <alpha-value>)',
        'warning-foreground': 'rgb(var(--color-warning-foreground) / <alpha-value>)',
        imdb: 'rgb(var(--color-imdb) / <alpha-value>)',
        'imdb-hover': 'rgb(var(--color-imdb-hover) / <alpha-value>)',
      },
    },
  },
  plugins: [],
} satisfies Config;
