import Database from 'better-sqlite3';
import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { initialMigration } from './migrations/001_initial.js';
import { matchCandidatesMigration } from './migrations/002_match_candidates.js';
import { ensureCandidateMediaType } from './migrations/003_candidate_media_type.js';
import { ensureImdbId } from './migrations/004_imdb_id.js';
import { shelvesMigration } from './migrations/005_shelves.js';
import { ensureMediaProbeSchema } from './migrations/006_media_probe.js';
import { ensureScanTitlesAdded } from './migrations/007_scan_titles_added.js';
import { ensureRunKind } from './migrations/008_run_kind.js';
import { ensureMetadataDisplayFields } from './migrations/009_metadata_display.js';
import { ensureCandidateEpisode } from './migrations/010_candidate_episode.js';
import { ensureMetadataMediaType } from './migrations/011_metadata_media_type.js';
import { ensureEpisodeColumns } from './migrations/012_episode_columns.js';
import { playbackProgressMigration } from './migrations/013_playback_progress.js';
import { ensureTorrentSearchToggle } from './migrations/014_torrent_search_toggle.js';
import { accessPinMigration } from './migrations/015_access_pin.js';
import { ensurePlaybackCollection } from './migrations/016_playback_collection.js';
import { downloadedSubtitlesMigration } from './migrations/017_downloaded_subtitles.js';

export function createDatabase(appDataPath: string): Database.Database {
  mkdirSync(appDataPath, { recursive: true });
  const db = new Database(join(appDataPath, 'library.sqlite'));
  db.pragma('foreign_keys = ON');
  db.pragma('journal_mode = WAL');
  db.pragma('busy_timeout = 5000');
  db.exec(initialMigration);
  db.exec(matchCandidatesMigration);
  ensureCandidateMediaType(db);
  ensureImdbId(db);
  db.exec(shelvesMigration);
  ensureMediaProbeSchema(db);
  ensureScanTitlesAdded(db);
  ensureRunKind(db);
  ensureMetadataDisplayFields(db);
  ensureCandidateEpisode(db);
  ensureMetadataMediaType(db);
  ensureEpisodeColumns(db);
  db.exec(playbackProgressMigration);
  ensureTorrentSearchToggle(db);
  db.exec(accessPinMigration);
  ensurePlaybackCollection(db);
  db.exec(downloadedSubtitlesMigration);
  return db;
}
